In [1]:
from sklearn.datasets import load_boston

In [2]:
boston_raw = load_boston()

In [3]:
boston_raw.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [4]:
for key in boston_raw:
    print(key+"\n", boston_raw[key])

data
 [[  6.32000000e-03   1.80000000e+01   2.31000000e+00 ...,   1.53000000e+01
    3.96900000e+02   4.98000000e+00]
 [  2.73100000e-02   0.00000000e+00   7.07000000e+00 ...,   1.78000000e+01
    3.96900000e+02   9.14000000e+00]
 [  2.72900000e-02   0.00000000e+00   7.07000000e+00 ...,   1.78000000e+01
    3.92830000e+02   4.03000000e+00]
 ..., 
 [  6.07600000e-02   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.96900000e+02   5.64000000e+00]
 [  1.09590000e-01   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.93450000e+02   6.48000000e+00]
 [  4.74100000e-02   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.96900000e+02   7.88000000e+00]]
target
 [ 24.   21.6  34.7  33.4  36.2  28.7  22.9  27.1  16.5  18.9  15.   18.9
  21.7  20.4  18.2  19.9  23.1  17.5  20.2  18.2  13.6  19.6  15.2  14.5
  15.6  13.9  16.6  14.8  18.4  21.   12.7  14.5  13.2  13.1  13.5  18.9
  20.   21.   24.7  30.8  34.9  26.6  25.3  24.7  21.2  19.3  20.   16.6
  14.4  19.4  

In [5]:
print(boston_raw["DESCR"])

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline

In [7]:
house_prices = pd.DataFrame(boston_raw["data"])

In [8]:
house_prices.head(5)

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [9]:
house_prices = pd.DataFrame(boston_raw["data"], columns=boston_raw["feature_names"])

In [10]:
house_prices["MEDV"] = boston_raw["target"]

In [11]:
house_prices.head(5)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [12]:
house_prices["CRIM"].mean()

3.5937607114624512

In [13]:
house_prices.head(5)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [17]:
house_sample = house_sample[["RM", "LSTAT"]]

In [14]:
house_sample = house_prices.sample(frac=0.7)

        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
        - LSTAT    % lower status of the population
        - MEDV     Median value of owner-occupied homes in $1000's

In [15]:
house_sample.head(5)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
212   0.21719   0.0  10.59   1.0  0.489  5.807  53.8  3.6526   4.0  277.0   
381  15.87440   0.0  18.10   0.0  0.671  6.545  99.1  1.5192  24.0  666.0   
469  13.07510   0.0  18.10   0.0  0.580  5.713  56.7  2.8237  24.0  666.0   
349   0.02899  40.0   1.25   0.0  0.429  6.939  34.5  8.7921   1.0  335.0   
431  10.06230   0.0  18.10   0.0  0.584  6.833  94.3  2.0882  24.0  666.0   

     PTRATIO       B  LSTAT  MEDV  
212     18.6  390.94  16.03  22.4  
381     20.2  396.90  21.08  10.9  
469     20.2  396.90  14.76  20.1  
349     19.7  389.85   5.89  26.6  
431     20.2   81.33  19.69  14.1

In [16]:
SQRT(B/1000)+0.63

NameError: name 'SQRT' is not defined

In [ ]:
from math import sqrt

In [ ]:
sqrt(house_sample["B"]/1000)+0.63

In [ ]:
def convert_to_fraction(b):
    return (sqrt(b/1000)+0.63)

In [ ]:
house_sample["bk"] = house_sample["B"].apply(lambda b: convert_to_fraction(b))

In [ ]:
house_sample["bk"].describe()

In [ ]:
house_sample.corr()

In [ ]:
house_prices.pop("MEDV")

In [ ]:
house_prices.head(5)

In [ ]:
house_prices["bk"] = house_prices["B"].apply(lambda b: convert_to_fraction(b))

In [ ]:
house_prices.head(5)

In [31]:
from sklearn.ensemble import RandomForestRegressor

In [32]:
from sklearn.model_selection import train_test_split

In [20]:
house_prices_bak = house_prices

In [22]:
house_prices = house_prices[["RM", "LSTAT"]]

In [26]:
X =house_prices.as_matrix()

In [27]:
y = boston_raw["target"]

In [28]:
X

array([[ 6.575,  4.98 ],
       [ 6.421,  9.14 ],
       [ 7.185,  4.03 ],
       ..., 
       [ 6.976,  5.64 ],
       [ 6.794,  6.48 ],
       [ 6.03 ,  7.88 ]])

In [33]:
y

array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,
        18.9,  15. ,  18.9,  21.7,  20.4,  18.2,  19.9,  23.1,  17.5,
        20.2,  18.2,  13.6,  19.6,  15.2,  14.5,  15.6,  13.9,  16.6,
        14.8,  18.4,  21. ,  12.7,  14.5,  13.2,  13.1,  13.5,  18.9,
        20. ,  21. ,  24.7,  30.8,  34.9,  26.6,  25.3,  24.7,  21.2,
        19.3,  20. ,  16.6,  14.4,  19.4,  19.7,  20.5,  25. ,  23.4,
        18.9,  35.4,  24.7,  31.6,  23.3,  19.6,  18.7,  16. ,  22.2,
        25. ,  33. ,  23.5,  19.4,  22. ,  17.4,  20.9,  24.2,  21.7,
        22.8,  23.4,  24.1,  21.4,  20. ,  20.8,  21.2,  20.3,  28. ,
        23.9,  24.8,  22.9,  23.9,  26.6,  22.5,  22.2,  23.6,  28.7,
        22.6,  22. ,  22.9,  25. ,  20.6,  28.4,  21.4,  38.7,  43.8,
        33.2,  27.5,  26.5,  18.6,  19.3,  20.1,  19.5,  19.5,  20.4,
        19.8,  19.4,  21.7,  22.8,  18.8,  18.7,  18.5,  18.3,  21.2,
        19.2,  20.4,  19.3,  22. ,  20.3,  20.5,  17.3,  18.8,  21.4,
        15.7,  16.2,

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [35]:
?? RandomForestRegressor

In [36]:
rfrgs = RandomForestRegressor()

In [37]:
rfrgs.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [39]:
rfrgs.feature_importances_

array([ 0.5528212,  0.4471788])

In [40]:
y_predicted = rfrgs.predict(X_test)

In [41]:
from sklearn.metrics import r2_score

In [42]:
r2_score(y_predicted, y_test)

0.68103919508194655

In [43]:
import pickle

In [46]:
pickle.dump(rfrgs, open("model_14122017.pickle", "wb"))

In [47]:
pickle.load(open("model_14122017.pickle", "rb"))

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [50]:
X_test[0]

array([ 6.416,  9.04 ])

In [51]:
rfrgs.predict([6.41, 9.04])

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 23.13])